#!/usr/bin/env tsx
// Generates docs/agent/STEPS.md from step definitions using the existing
// parse-steps-for-llm.ts CLI (it prints JSON to stdout).

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

interface StepSummary {
  pattern: string;
  description: string;
  line: number;
}

interface FileSummary {
  fileName: string;
  steps: StepSummary[];
}

interface ParserOutput {
  metadata: { totalFiles: number; totalSteps: number };
  files: FileSummary[];
}

const root = path.resolve(__dirname, '..');
const parserPath = path.join(root, 'support/mcp/utils/parse-steps-for-llm.ts');
const outputPath = path.join(root, 'docs/agent/STEPS.md');

const json = execFileSync('npx', ['tsx', parserPath], { cwd: root, encoding: 'utf-8' });
const data: ParserOutput = JSON.parse(json);

const lines: string[] = [
  '# Step Reference (generated)',
  '',
  `Full list of available Gherkin steps. Generated by \`yarn steps:docs\` — do not edit manually.`,
  '',
  `Total: **${data.metadata.totalSteps} steps** in ${data.metadata.totalFiles} files. Search here before writing a new step; add new steps only to \`steps/domain/\`.`,
  '',
];

for (const file of data.files) {
  lines.push(`## ${file.fileName}`, '');
  for (const step of file.steps) {
    lines.push(`- \`${step.pattern}\``);
    if (step.description) {
      const firstLine = step.description.split('\n')[0].trim();
      if (firstLine) lines.push(`  - ${firstLine}`);
    }
  }
  lines.push('');
}

fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
console.log(`Wrote ${outputPath}: ${data.metadata.totalSteps} steps from ${data.metadata.totalFiles} files`);
